apiVersion: v1
kind: Service
metadata:
  name: {{ include "ppe-compliance-monitor.fullname" . }}-backend
  labels:
    {{- include "ppe-compliance-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "ppe-compliance-monitor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
