apiVersion: v1
kind: Service
metadata:
  name: {{ include "ppe-compliance-monitor.fullname" . }}-frontend
  labels:
    {{- include "ppe-compliance-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "ppe-compliance-monitor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
