{{- if .Values.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ printf "%s-fe" .Release.Name | trunc 30 | trimSuffix "-" }}
  labels:
    {{- include "ppe-compliance-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.openshift.sharedHost }}
  host: {{ .Values.openshift.sharedHost | quote }}
  {{- else if .Values.openshift.route.host }}
  host: {{ .Values.openshift.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "ppe-compliance-monitor.fullname" . }}-frontend
  port:
    targetPort: http
  {{- if .Values.openshift.route.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
