{{- if and .Values.openshift.roleBinding.enabled .Values.openshift.scc.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ppe-compliance-monitor.fullname" . }}-scc
  labels:
    {{- include "ppe-compliance-monitor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:{{ .Values.openshift.scc.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.openshift.roleBinding.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
